[build]
  command = "npx prisma generate && npx prisma migrate deploy && npm run build --debug"
  publish = ".next"
  edge_functions = "netlify/edge-functions"


[[edge_functions]]
  function = "next"
  path = "/*"

[[plugins]]
  package = "@netlify/plugin-nextjs"